"""empty message

Revision ID: a0d358cfef4f
Revises: 86b6de7c75e1
Create Date: 2020-09-25 17:14:47.602678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d358cfef4f'
down_revision = '86b6de7c75e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('releaseDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'releaseDate')
    # ### end Alembic commands ###
